language: java
jdk:
- openjdk8
branches:
  only:
  - master
install: mvn clean package -Ph2
deploy:
  provider: heroku
  api_key:
    secure: bBmzSbgl0W8Bh/6uU54NvnO22NwFls6WdPGbAuUejeSjGEF/x9ch0v2DyyaGKLrSGOQFpqvepEHfWNNyrNXd4oApl9+PiYh1c9S3rxlQstAUX1YbkKEQitDkX1g0PPxhHU45+wNQG6AYxOlX/3vQRq5mSU1oDumNqfwu20ZXIg6lfmlTWdqQgxQJ1tRUtQ0hMAllPplCQgVOzvhpuUTHIdCbg7yuxJ90zEciRu9KN70GpF3dod68B6rqV441eEorWeVNqXXVQoYzJvIoPAoUVaqumMAhvUx2eu9GVDwH9d3g8Yyg/ax3n5uLoiajxTAvf/58TAtccNy4jvoIXyMeMObQv8jFQysHyrwOpPAV5fQt+ORUsWx1OXCNHaRwnxuhOb++f+QDEOyBJ/L+8Drgp/E5BMA4FzwKI+C2peiP8jX1T7pW/QWEzuVLi6Ia6edjq90sILRNDqXRWo8JDuB5omps5Led4/FAPaavyfvpXFsc/LYWXhnuriyesLjv9EU/aiNWyX5Tq0YpmjvqGvdukVsCU4HA+NGWZg1kgTBeW5QUkMby/HtphGzpJYESwOne2V0V1mBN0/bdIjMButpj1WLl0nw4WGQwkG0tEgnRJjT6XWjfQu08SzjcZQor8XU1n4Q9SLDoahZoaJmHVLsMQy8j6rfA3HX6d9vdz1FBy/Q=
  app:
    master: spring-mvc-start-demo
